### ISSUE TITLE
fit columns

### ISSUE THREAD

**Issue by falberto** [hzjken/HFT-price-prediction#1]
I'm a little confused, to train the model I need to have the values of the labels filled in the CSV file(_1s_side,_3s_side,_5s_side)?
Isn't that what the model proposes to answer?

Thank's for your time.

**Comment by hzjken** [comment]
Hi @falberto ,

The ultimate goal of the model is to be able to accurately predict whether price is going up or down in the future during real trading, therefore it needs to learn how to do the classification from the labels (_1s_side,_3s_side,_5s_side) and the attributes we create right now. That's why labels are needed during this training stage. Later on when we have no such  (_1s_side,_3s_side,_5s_side) labels during real trading, it's when the model really come into effect.

I admit it might be a bit confusing as I didn't include the validation of the model accuracy here, the output is just a  function that could be used for later prediction. But actually accuracy can be checked during the parameter tuning part.

Not sure if this answer your question clearly, feel free to let me know more of your thoughts.

**Comment by falberto** [comment]
thank you for your answer, After I sended my question I did some research and figure out that the model need info to train properly. Exactly what you are explaining to me now.

Thank you very much.

Did you use this model in a live trade? I'm trying to collect some data to apply it in a live market.

**Comment by hzjken** [comment]
I haven't used it in live trade yet. As mentioned in the markdown, this project is only a data science hands on excercise from a HFT company. But feel free to have a try in live market. As I am also not sure about its performance in live market, I will suggest you to apply it in simulation environment first.
